# Nordic-darker color palette
#1F2335	user
#3b4252	dir
#292E42	git
#4c566a	version
#3B4261	doc (from dracula color palette)
#414868	time (from dracula color palette)

# some extra symbols
# 
# 

format = """
[░▒▓](#1F2335)\
$os\
$username\
[](bg:#3b4252 fg:#1F2335)\
$directory\
[](fg:#3b4252 bg:#292E42)\
$git_branch\
$git_status\
[](fg:#292E42 bg:#4c566a)\
$c\
$python\
$elixir\
$elm\
$golang\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
[](fg:#4c566a bg:#3B4261)\
$docker_context\
[](fg:#3B4261 bg:#414868)\
$time\
[ ](fg:#414868)\
\n
$cmd_duration\
$character\
"""
#add_newline = false

[line_break]
disabled = false

[username]
show_always = true
style_user = "bg:#1F2335"
style_root = "bg:#C0CAF5"
format = '[ $user ]($style)'
disabled = false

[os]
style = "bg:#C0CAF5"
disabled = true # Disabled by default

[directory]
style = "bg:#3b4252"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[c]
symbol = " "
style = "bg:#4c566a"
format = '[ $symbol ($version) ]($style)'

[python]
symbol = " "
style = "bg:#4c566a"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:#3B4261"
format = '[ $symbol $context ]($style) $path'

[elixir]
symbol = " "
style = "bg:#292E42"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:#292E42"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bg:#292E42"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#292E42"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:#292E42"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:#292E42"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:#292E42"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:#292E42"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#292E42"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = " "
style = "bg:##292E42"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:#292E42"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = " "
style = "bg:#292E42"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#414868"
format = '[  $time ]($style)'

[character]
success_symbol = '[ ➜](#414868)'
error_symbol = '[ ➜](bold red)'
#style = "bg:#414868"

[cmd_duration]
min_time = 500
format = ' [$duration](#414868)'