#!/usr/bin/env sh

# Shared variables for the hypr helper scripts

ConfDir="${XDG_CONFIG_HOME:-$HOME/.config}"

# theme var
gtkTheme=`gsettings get org.gnome.desktop.interface gtk-theme | sed "s/'//g"`
gtkIcon=`gsettings get org.gnome.desktop.interface icon-theme | sed "s/'//g"`
gtkMode=`gsettings get org.gnome.desktop.interface color-scheme | sed "s/'//g" | awk -F '-' '{print $2}'`

# hypr var
hypr_border=`hyprctl -j getoption decoration:rounding | jq '.int'`
hypr_width=`hyprctl -j getoption general:border_size | jq '.int'`
